"""Creating a login. The one write operation, and what keeps it safe.

The password is generated by 1Password, so no credential passes through this
process. These tests hold that line: they assert on the command built, not
just on the result.
"""

import json
import os
import unittest
from unittest.mock import MagicMock, patch

from support import IsolatedRuntimeDir
from omapass import service


class TestCreateLogin(IsolatedRuntimeDir):
    def setUp(self):
        super().setUp()
        os.chmod(self.runtime, 0o700)
        self.service = service.OmaPassService()

    def _run(self, **kwargs):
        created = json.dumps({"id": "new1", "title": kwargs.get("title", "T"),
                              "vault": {"name": "Personal"}})
        with patch.object(self.service, "check_op_installed", return_value=True):
            with patch("subprocess.run", return_value=MagicMock(
                    returncode=0, stdout=created, stderr="")) as run:
                with patch.object(self.service, "sync"):
                    res = self.service.create_login(**kwargs)
        return res, run.call_args[0][0] if run.call_args else []

    def test_the_password_is_generated_by_op_not_by_us(self):
        res, argv = self._run(title="GitHub", username="octocat")
        self.assertTrue(res["ok"])
        recipe = [a for a in argv if a.startswith("--generate-password=")]
        self.assertEqual(len(recipe), 1)
        # Nothing resembling a password is handed to op or held here.
        self.assertNotIn("password", " ".join(argv).replace("--generate-password", ""))
        self.assertNotIn("password", res)

    def test_the_users_data_never_travels_in_argv(self):
        """Title and username are not secrets, but they are still not argv material."""
        res, argv = self._run(title="My Bank", username="a.person@example.com",
                              url="https://bank.example.com")
        joined = " ".join(argv)
        self.assertNotIn("My Bank", joined)
        self.assertNotIn("a.person@example.com", joined)
        self.assertTrue(any(a.startswith("--template=") for a in argv))

    def test_the_template_is_private_and_removed_afterwards(self):
        seen = {}

        def capture(cmd, *a, **k):
            path = [c for c in cmd if c.startswith("--template=")][0].split("=", 1)[1]
            seen["path"] = path
            seen["mode"] = os.stat(path).st_mode & 0o777
            with open(path) as fh:
                seen["body"] = json.load(fh)
            return MagicMock(returncode=0, stdout="{}", stderr="")

        with patch.object(self.service, "check_op_installed", return_value=True):
            with patch("subprocess.run", side_effect=capture):
                with patch.object(self.service, "sync"):
                    self.service.create_login(title="X", username="u")

        self.assertEqual(seen["mode"], 0o600)
        self.assertEqual(seen["body"]["title"], "X")
        self.assertFalse(os.path.exists(seen["path"]), "template outlived the command")

    def test_a_title_is_required(self):
        with patch.object(self.service, "check_op_installed", return_value=True):
            self.assertFalse(self.service.create_login(title="   ")["ok"])

    def test_a_bogus_recipe_is_refused_before_op_sees_it(self):
        with patch.object(self.service, "check_op_installed", return_value=True):
            with patch("subprocess.run") as run:
                res = self.service.create_login(title="X", password_recipe="; rm -rf /")
        self.assertFalse(res["ok"])
        run.assert_not_called()

    def test_a_non_web_url_is_refused(self):
        with patch.object(self.service, "check_op_installed", return_value=True):
            with patch("subprocess.run") as run:
                res = self.service.create_login(title="X", url="javascript:alert(1)")
        self.assertFalse(res["ok"])
        run.assert_not_called()

    def test_a_bare_host_is_stored_as_https(self):
        _, argv = self._run(title="X", url="example.com")
        path = [a for a in argv if a.startswith("--template=")][0]
        self.assertTrue(path)

    def test_dry_run_asks_op_to_validate_only(self):
        res, argv = self._run(title="X", dry_run=True)
        self.assertIn("--dry-run", argv)
        self.assertTrue(res["dryRun"])

    def test_a_real_run_does_not_ask_for_a_dry_run(self):
        _, argv = self._run(title="X")
        self.assertNotIn("--dry-run", argv)

    def test_creating_refuses_once_the_vault_locked_mid_request(self):
        def lock_during(cmd, *a, **k):
            self.service.lock_epoch += 1
            return MagicMock(returncode=0, stdout="{}", stderr="")

        with patch.object(self.service, "check_op_installed", return_value=True):
            with patch("subprocess.run", side_effect=lock_during):
                with patch.object(self.service, "sync") as sync:
                    res = self.service.create_login(title="X")

        self.assertFalse(res["ok"])
        sync.assert_not_called()

    def test_a_new_item_triggers_a_sync_so_it_appears_in_the_list(self):
        created = json.dumps({"id": "n", "title": "X", "vault": {"name": "P"}})
        with patch.object(self.service, "check_op_installed", return_value=True):
            with patch("subprocess.run", return_value=MagicMock(
                    returncode=0, stdout=created, stderr="")):
                with patch.object(self.service, "sync") as sync:
                    self.service.create_login(title="X")
        # started on a thread; give it a moment to run
        import time
        time.sleep(0.2)
        sync.assert_called()

    def test_a_typed_password_never_reaches_argv(self):
        """It has to travel somehow; a 0600 file in tmpfs beats /proc."""
        seen = {}

        def capture(cmd, *a, **k):
            path = [c for c in cmd if c.startswith("--template=")][0].split("=", 1)[1]
            seen["argv"] = cmd
            seen["mode"] = os.stat(path).st_mode & 0o777
            with open(path) as fh:
                seen["body"] = json.load(fh)
            seen["path"] = path
            return MagicMock(returncode=0, stdout="{}", stderr="")

        with patch.object(self.service, "check_op_installed", return_value=True):
            with patch("subprocess.run", side_effect=capture):
                with patch.object(self.service, "sync"):
                    self.service.create_login(title="X", password="hunter2")

        self.assertNotIn("hunter2", " ".join(seen["argv"]))
        self.assertEqual(seen["mode"], 0o600)
        self.assertFalse(os.path.exists(seen["path"]), "the typed password outlived the command")
        pw = [f for f in seen["body"]["fields"] if f["id"] == "password"]
        self.assertEqual(pw[0]["value"], "hunter2")

    def test_a_typed_password_replaces_generation(self):
        _, argv = self._run(title="X", password="hunter2")
        self.assertFalse([a for a in argv if a.startswith("--generate-password")])

    def test_generation_is_the_default(self):
        _, argv = self._run(title="X")
        self.assertTrue([a for a in argv if a.startswith("--generate-password")])

    def test_a_typed_password_skips_recipe_validation(self):
        """The recipe is irrelevant when the user supplied the password."""
        with patch.object(self.service, "check_op_installed", return_value=True):
            with patch("subprocess.run", return_value=MagicMock(
                    returncode=0, stdout="{}", stderr="")):
                with patch.object(self.service, "sync"):
                    res = self.service.create_login(title="X", password="p", password_recipe="junk")
        self.assertTrue(res["ok"])

    def test_dispatch_routes_create_login(self):
        with patch.object(self.service, "create_login", return_value={"ok": True}) as c:
            self.service.dispatch({"action": "create_login", "title": "X", "dryRun": True})
        self.assertTrue(c.call_args.kwargs["dry_run"])


if __name__ == "__main__":
    unittest.main()
