import QtQuick
import QtQuick.Layouts
import qs.Commons
import qs.Ui
import "../Model.js" as Model

// One labelled row of the create form.
//
// The widget is chosen from 1Password's own field type, so adding a category
// to Model.CREATE_SPECS is enough to get a form: no QML changes needed. A
// field type this does not know about still renders as text rather than
// disappearing from the form.
ColumnLayout {
  id: root

  required property Theme theme
  required property var spec          // one entry from Model.createSpec().fields
  property string value: ""
  property string error: ""
  // Only meaningful for a secret field: while true the value is generated by
  // 1Password and never typed here.
  property bool generated: true

  signal edited(string value)
  signal generateToggled(bool generated)
  signal submitted()

  readonly property string kind: Model.inputKindFor(spec.type)
  readonly property bool isSecret: kind === "secret"
  readonly property bool isMultiline: kind === "multiline"
  // Only the field the category can have generated offers the toggle.
  property bool generatable: false
  property alias input: field

  Layout.fillWidth: true
  spacing: Style.space(3)

  RowLayout {
    Layout.fillWidth: true
    spacing: Style.space(6)

    Text {
      text: root.spec.label.toUpperCase() + (root.spec.required ? " *" : "")
      font.family: root.theme.fontFamily
      font.pixelSize: Style.font.caption - 1
      font.bold: true
      color: root.error ? root.theme.urgent : root.theme.dim
    }

    Item { Layout.fillWidth: true }

    // A generated password is the default because it never exists outside
    // 1Password. Typing one is allowed, and says so.
    Text {
      visible: root.isSecret && root.generatable
      text: root.generated ? "generated by 1Password" : "typed here"
      font.family: root.theme.fontFamily
      font.pixelSize: Style.font.caption - 1
      color: root.generated ? root.theme.dim : root.theme.urgent
    }

    Button {
      visible: root.isSecret && root.generatable
      text: root.generated ? "Type it" : "Generate"
      accent: root.theme.accent
      horizontalPadding: Style.space(8)
      verticalPadding: Style.space(2)
      onClicked: root.generateToggled(!root.generated)
    }
  }

  TextField {
    id: field
    Layout.fillWidth: true
    visible: !(root.isSecret && root.generatable && root.generated) && !root.isMultiline
    text: root.value
    password: root.isSecret
    placeholderText: root.spec.placeholder || ""
    foreground: root.theme.foreground
    accent: root.error ? root.theme.urgent : root.theme.accent
    onTextChanged: if (text !== root.value) root.edited(text)
    Keys.onReturnPressed: root.submitted()
    Keys.onEnterPressed: root.submitted()
  }

  // Stands in for the input when the password is generated, so the row keeps
  // its height and the form does not jump as the toggle is used.
  BorderSurface {
    Layout.fillWidth: true
    Layout.preferredHeight: Style.spacing.controlHeight
    visible: root.isSecret && root.generatable && root.generated
    radius: Style.cornerRadius
    color: Qt.rgba(root.theme.foreground.r, root.theme.foreground.g, root.theme.foreground.b, 0.04)
    borderSpec: Border.controlSpec("normal", root.theme.foreground, root.theme.accent)

    Text {
      anchors.left: parent.left
      anchors.leftMargin: Style.spacing.controlPaddingX
      anchors.verticalCenter: parent.verticalCenter
      text: "\u{f0306}  1Password will generate and store it"
      font.family: root.theme.fontFamily
      font.pixelSize: Style.font.body
      color: root.theme.dim
      elide: Text.ElideRight
      width: parent.width - Style.spacing.controlPaddingX * 2
    }
  }

  // A note is the one field worth more than one line.
  BorderSurface {
    visible: root.isMultiline
    Layout.fillWidth: true
    Layout.preferredHeight: Style.space(96)
    radius: Style.cornerRadius
    color: Qt.rgba(root.theme.foreground.r, root.theme.foreground.g, root.theme.foreground.b, 0.04)
    borderSpec: Border.controlSpec(noteArea.activeFocus ? "focus" : "normal",
                                   root.theme.foreground, root.theme.accent)

    Flickable {
      anchors.fill: parent
      anchors.margins: Style.space(8)
      contentWidth: width
      contentHeight: noteArea.implicitHeight
      clip: true

      TextEdit {
        id: noteArea
        width: parent.width
        text: root.value
        font.family: root.theme.fontFamily
        font.pixelSize: Style.font.body
        color: root.theme.foreground
        selectByMouse: true
        wrapMode: TextEdit.Wrap
        onTextChanged: if (text !== root.value) root.edited(text)
      }
    }
  }

  Text {
    visible: root.error.length > 0
    Layout.fillWidth: true
    text: root.error
    font.family: root.theme.fontFamily
    font.pixelSize: Style.font.caption - 1
    color: root.theme.urgent
    wrapMode: Text.Wrap
  }
}
